// Code generated by hyperrr. DO NOT EDIT.
package main

import (
	_ "github.com/GoHyperrr/auth/apikey"
	_ "github.com/GoHyperrr/auth/emailpass"
	_ "github.com/GoHyperrr/commerce/product"
	_ "github.com/GoHyperrr/commerce/store"
	_ "github.com/GoHyperrr/commerce/customer"
	_ "github.com/GoHyperrr/commerce/cart"
	_ "github.com/GoHyperrr/commerce/order"
	_ "github.com/GoHyperrr/commerce/finance"
	_ "github.com/GoHyperrr/notification"
	_ "github.com/GoHyperrr/commerce/fulfillment"
	_ "github.com/GoHyperrr/commerce/support"
	_ "github.com/GoHyperrr/commerce/marketing"
	_ "github.com/GoHyperrr/commerce/search"
	_ "github.com/GoHyperrr/commerce/taxonomy"
	_ "github.com/GoHyperrr/commerce/analytics"
)
