// Code generated by hyperrr. DO NOT EDIT.
package main

import (
	_ "github.com/GoHyperrr/auth/apikey"
	_ "github.com/GoHyperrr/auth/emailpass"
	_ "github.com/GoHyperrr/commerce/product"
	_ "github.com/GoHyperrr/commerce/store"
	_ "github.com/GoHyperrr/commerce/customer"
	_ "github.com/GoHyperrr/commerce/cart"
	_ "github.com/GoHyperrr/commerce/order"
	_ "github.com/GoHyperrr/commerce/payments"
	_ "github.com/GoHyperrr/commerce/taxonomy"
	_ "github.com/GoHyperrr/commerce/seo"
	_ "github.com/GoHyperrr/notification"
)
