package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/GoHyperrr/hyperrr/internal/context/graph/model"
)

// GetWorkflowLineage is the resolver for the getWorkflowLineage field.
func (r *queryResolver) GetWorkflowLineage(ctx context.Context, id string) (*model.WorkflowLineage, error) {
	lineage, err := r.Projector.GetLineage(id)
	if err != nil {
		return nil, err
	}

	return mapToModel(lineage), nil
}

// ListLineages is the resolver for the listLineages field.
func (r *queryResolver) ListLineages(ctx context.Context) ([]*model.WorkflowLineage, error) {
	lineages := r.Projector.ListLineages()
	res := make([]*model.WorkflowLineage, 0, len(lineages))
	for _, l := range lineages {
		res = append(res, mapToModel(l))
	}
	return res, nil
}

// Events is the resolver for the events field.
func (r *workflowLineageResolver) Events(ctx context.Context, obj *model.WorkflowLineage) ([]*model.Event, error) {
	lineage, err := r.Projector.GetLineage(obj.ID)
	if err != nil {
		return nil, err
	}
	res := mapToModel(lineage)
	return res.Events, nil
}

// RelatedLineages is the resolver for the relatedLineages field.
func (r *workflowLineageResolver) RelatedLineages(ctx context.Context, obj *model.WorkflowLineage) ([]*model.WorkflowLineage, error) {
	related, err := r.Projector.GetRelatedLineages(obj.ID)
	if err != nil {
		return nil, err
	}
	res := make([]*model.WorkflowLineage, 0, len(related))
	for _, l := range related {
		res = append(res, mapToModel(l))
	}
	return res, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// WorkflowLineage returns WorkflowLineageResolver implementation.
func (r *Resolver) WorkflowLineage() WorkflowLineageResolver { return &workflowLineageResolver{r} }

type queryResolver struct{ *Resolver }
type workflowLineageResolver struct{ *Resolver }
