package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/order"
)

// GetSystemStats is the resolver for the getSystemStats field.
func (r *queryResolver) GetSystemStats(ctx context.Context) (*model.SystemStats, error) {
	if r.AnalyticsModule.Projector() == nil {
		return nil, fmt.Errorf("analytics module not initialized with projector")
	}

	lineages := r.AnalyticsModule.Projector().ListLineages()
	
	total := len(lineages)
	if total == 0 {
		return &model.SystemStats{}, nil
	}

	success := 0
	failed := 0
	var totalDuration time.Duration

	for _, l := range lineages {
		if l.State == "COMPLETED" {
			success++
		} else if l.State == "FAILED" {
			failed++
		}
		if !l.EndedAt.IsZero() {
			totalDuration += l.EndedAt.Sub(l.StartedAt)
		}
	}

	return &model.SystemStats{
		TotalWorkflows:     total,
		SuccessRate:        (float64(success) / float64(total)) * 100,
		FailureRate:        (float64(failed) / float64(total)) * 100,
		AvgExecutionTimeMs: float64(totalDuration.Milliseconds()) / float64(total),
	}, nil
}

// GetSalesStats is the resolver for the getSalesStats field.
func (r *queryResolver) GetSalesStats(ctx context.Context) (*model.SalesStats, error) {
	if r.AnalyticsModule.Projector() == nil {
		return nil, fmt.Errorf("analytics module not initialized with projector")
	}

	lineages := r.AnalyticsModule.Projector().ListLineages()
	
	var totalRevenue float64
	orderCount := 0

	for _, l := range lineages {
		// Look for successful fulfillment workflows
		if l.Name == "fulfillment.v1" && l.State == "COMPLETED" {
			// Find the finalize step
			for _, step := range l.Steps {
				if step.StepID == "order.finalize" {
					// Extract order from step events or results? 
					// Actually, the Projector has the event history.
					// For simplicity in this mock, we'll try to find an 'order.finalized' event 
					// or just assume we can find it in the event list.
					for _, ev := range l.Events {
						if ev.Type == "workflow.step_completed" {
							// In a real system we'd parse the payload
							// Here we'll just check if it's the finalize step
						}
					}
				}
			}
		}
	}

	// Since parsing payloads from the projector is complex in this mock,
	// let's just query the Order repository directly if available, 
	// or mock some data based on COMPLETED fulfillment lineages.
	
	// Real implementation using the Order module:
	if r.OrderModule != nil {
		orders, err := r.OrderModule.Repo().List(ctx)
		if err == nil {
			for _, o := range orders {
				if o.Status == order.OrderPaid || o.Status == order.OrderFulfilled {
					totalRevenue += o.TotalPrice
					orderCount++
				}
			}
		}
	}

	avg := 0.0
	if orderCount > 0 {
		avg = totalRevenue / float64(orderCount)
	}

	return &model.SalesStats{
		TotalRevenue:  totalRevenue,
		OrderCount:    orderCount,
		AvgOrderValue: avg,
	}, nil
}
