package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/order"
	ctxEngine "github.com/GoHyperrr/hyperrr/internal/context"
)

// GetSystemStats is the resolver for the getSystemStats field.
func (r *queryResolver) GetSystemStats(ctx context.Context) (*model.SystemStats, error) {
	if r.AnalyticsModule.Projector() == nil {
		return nil, fmt.Errorf("analytics module not initialized with projector")
	}

	lineages := r.AnalyticsModule.Projector().ListLineages()
	
	total := len(lineages)
	if total == 0 {
		return &model.SystemStats{}, nil
	}

	success := 0
	failed := 0
	var totalDuration time.Duration

	for _, l := range lineages {
		if l.GetState() == "COMPLETED" {
			success++
		} else if l.GetState() == "FAILED" {
			failed++
		}
		if l.GetEndedAt() != nil && !l.GetEndedAt().IsZero() {
			totalDuration += l.GetEndedAt().Sub(l.GetStartedAt())
		}
	}

	return &model.SystemStats{
		TotalWorkflows:     total,
		SuccessRate:        (float64(success) / float64(total)) * 100,
		FailureRate:        (float64(failed) / float64(total)) * 100,
		AvgExecutionTimeMs: float64(totalDuration.Milliseconds()) / float64(total),
	}, nil
}

// GetSalesStats is the resolver for the getSalesStats field.
func (r *queryResolver) GetSalesStats(ctx context.Context) (*model.SalesStats, error) {
	if r.AnalyticsModule.Projector() == nil {
		return nil, fmt.Errorf("analytics module not initialized with projector")
	}

	lineages := r.AnalyticsModule.Projector().ListLineages()
	
	var totalRevenue float64
	orderCount := 0
	orderIDs := make(map[string]bool)

	for _, l := range lineages {
		// Look for successful fulfillment workflows
		if l.GetName() == "fulfillment.v1" && l.GetState() == "COMPLETED" {
			// Extract revenue from lineage events
			conc, ok := l.(*ctxEngine.Lineage)
			if ok {
				for _, ev := range conc.Events {
					if ev.Type == "order.paid" {
						if p, ok := ev.Payload.(map[string]any); ok {
							if total, ok := p["total_price"].(float64); ok {
								totalRevenue += total
								orderCount++
								if id, ok := p["order_id"].(string); ok {
									orderIDs[id] = true
								}
								break
							}
						}
					}
				}
			}
		}
	}

	// Secondary check: Database reconciliation
	if r.OrderModule != nil {
		orders, err := r.OrderModule.Repo().List(ctx)
		if err == nil {
			for _, o := range orders {
				if (o.Status == order.OrderPaid || o.Status == order.OrderFulfilled) && !orderIDs[o.ID] {
					totalRevenue += o.TotalPrice
					orderCount++
					orderIDs[o.ID] = true
				}
			}
		}
	}

	avg := 0.0
	if orderCount > 0 {
		avg = totalRevenue / float64(orderCount)
	}

	return &model.SalesStats{
		TotalRevenue:  totalRevenue,
		OrderCount:    orderCount,
		AvgOrderValue: avg,
	}, nil
}
