package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/cart"
	"github.com/GoHyperrr/hyperrr/internal/workflow"
)

// AddItemToCart is the resolver for the addItemToCart field.
func (r *mutationResolver) AddItemToCart(ctx context.Context, cartID string, input model.AddItemInput) (*model.Cart, error) {
	wf := &workflow.Workflow{
		Name: "cart.add_item",
		Steps: []workflow.Step{
			{ID: "add", Uses: "cart.add_item"},
		},
	}

	workflowInput := map[string]any{
		"cart_id":    cartID,
		"product_id": input.ProductID,
		"quantity":   input.Quantity,
		"price":      input.Price,
	}

	execID := fmt.Sprintf("add_item_%d", time.Now().UnixNano())
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	domainRes, ok := results["add"].(*cart.Cart)
	if !ok {
		return nil, fmt.Errorf("failed to retrieve updated cart from workflow results")
	}

	return mapCartToModel(domainRes), nil
}

// RemoveItemFromCart is the resolver for the removeItemFromCart field.
func (r *mutationResolver) RemoveItemFromCart(ctx context.Context, cartID string, itemID string) (*model.Cart, error) {
	wf := &workflow.Workflow{
		Name: "cart.remove_item",
		Steps: []workflow.Step{
			{ID: "remove", Uses: "cart.remove_item"},
		},
	}

	workflowInput := map[string]any{
		"cart_id": cartID,
		"item_id": itemID,
	}

	execID := fmt.Sprintf("remove_item_%d", time.Now().UnixNano())
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	domainRes, ok := results["remove"].(*cart.Cart)
	if !ok {
		return nil, fmt.Errorf("failed to retrieve updated cart from workflow results")
	}

	return mapCartToModel(domainRes), nil
}

// CheckoutCart is the resolver for the checkoutCart field.
func (r *mutationResolver) CheckoutCart(ctx context.Context, cartID string) (bool, error) {
	wf := &workflow.Workflow{
		Name: "cart.checkout",
		Steps: []workflow.Step{
			{ID: "checkout", Uses: "cart.checkout"},
		},
	}

	workflowInput := map[string]any{
		"cart_id": cartID,
	}

	execID := fmt.Sprintf("checkout_%d", time.Now().UnixNano())
	_, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return false, err
	}

	return true, nil
}

// GetCart is the resolver for the getCart field.
func (r *queryResolver) GetCart(ctx context.Context, id string) (*model.Cart, error) {
	c, err := r.CartModule.Repo().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapCartToModel(c), nil
}

// GetActiveCart is the resolver for the getActiveCart field.
func (r *queryResolver) GetActiveCart(ctx context.Context, customerID string) (*model.Cart, error) {
	c, err := r.CartModule.Repo().GetActiveByCustomerID(ctx, customerID)
	if err != nil {
		// If not found, create a new one
		newCart := &cart.Cart{
			ID:         fmt.Sprintf("cart_%d", time.Now().UnixNano()),
			CustomerID: customerID,
			Status:     cart.CartActive,
		}
		if err := r.CartModule.Repo().Save(ctx, newCart); err != nil {
			return nil, err
		}
		return mapCartToModel(newCart), nil
	}
	return mapCartToModel(c), nil
}
