package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/commerce/cart"
	"github.com/google/uuid"
)

// AddItemToCart is the resolver for the addItemToCart field.
func (r *mutationResolver) AddItemToCart(ctx context.Context, cartID string, input model.AddItemInput) (*model.Cart, error) {
	wf, err := r.Registry.Get("cart.add")
	if err != nil {
		return nil, err
	}

	workflowInput := map[string]any{
		"cart_id":    cartID,
		"product_id": input.ProductID,
		"quantity":   input.Quantity,
		"price":      input.Price,
	}

	execID := "add_item_" + uuid.New().String()
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	resRaw, ok := results["add"]
	if !ok {
		return nil, fmt.Errorf("failed to retrieve updated cart from workflow results")
	}

	resMap, ok := resRaw.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("invalid result format from add step")
	}

	var domainRes cart.Cart
	if err := decodeResult(resMap["cart"], &domainRes); err != nil {
		return nil, fmt.Errorf("invalid cart type in results: %w", err)
	}

	return mapCartToModel(&domainRes), nil
}

// RemoveItemFromCart is the resolver for the removeItemFromCart field.
func (r *mutationResolver) RemoveItemFromCart(ctx context.Context, cartID string, itemID string) (*model.Cart, error) {
	wf, err := r.Registry.Get("cart.remove")
	if err != nil {
		return nil, err
	}

	workflowInput := map[string]any{
		"cart_id": cartID,
		"item_id": itemID,
	}

	execID := "remove_item_" + uuid.New().String()
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	resRaw, ok := results["remove"]
	if !ok {
		return nil, fmt.Errorf("failed to retrieve updated cart from workflow results")
	}

	resMap, ok := resRaw.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("invalid result format from remove step")
	}

	var domainRes cart.Cart
	if err := decodeResult(resMap["cart"], &domainRes); err != nil {
		return nil, fmt.Errorf("invalid cart type in results: %w", err)
	}

	return mapCartToModel(&domainRes), nil
}

// CheckoutCart is the resolver for the checkoutCart field.
func (r *mutationResolver) CheckoutCart(ctx context.Context, cartID string) (bool, error) {
	wf, err := r.Registry.Get("cart.checkout")
	if err != nil {
		return false, err
	}

	workflowInput := map[string]any{
		"cart_id": cartID,
	}

	execID := "checkout_" + uuid.New().String()
	_, err = r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return false, err
	}

	return true, nil
}

// GetCart is the resolver for the getCart field.
func (r *queryResolver) GetCart(ctx context.Context, id string) (*model.Cart, error) {
	c, err := r.CartModule.Repo().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapCartToModel(c), nil
}

// GetActiveCart is the resolver for the getActiveCart field.
func (r *queryResolver) GetActiveCart(ctx context.Context, customerID string) (*model.Cart, error) {
	c, err := r.CartModule.Repo().GetActiveByCustomerID(ctx, customerID)
	if err != nil {
		// If not found, create a new one
		newCart := &cart.Cart{
			ID:         "cart_" + uuid.New().String(),
			CustomerID: customerID,
			Status:     cart.CartActive,
		}
		if err := r.CartModule.Repo().Save(ctx, newCart); err != nil {
			return nil, err
		}
		return mapCartToModel(newCart), nil
	}
	return mapCartToModel(c), nil
}
