package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	ctxEngine "github.com/GoHyperrr/hyperrr/internal/context"
)

// GetWorkflowLineage is the resolver for the getWorkflowLineage field.
func (r *queryResolver) GetWorkflowLineage(ctx context.Context, id string) (*model.WorkflowLineage, error) {
	lineage, err := r.Projector.GetLineage(id)
	if err != nil {
		return nil, err
	}

	return mapToModel(lineage), nil
}

// ListLineages is the resolver for the listLineages field.
func (r *queryResolver) ListLineages(ctx context.Context) ([]*model.WorkflowLineage, error) {
	lineages := r.Projector.ListLineages()
	res := make([]*model.WorkflowLineage, 0, len(lineages))
	for _, l := range lineages {
		conc, ok := l.(*ctxEngine.Lineage)
		if ok {
			res = append(res, mapToModel(conc))
		}
	}
	return res, nil
}

// Events is the resolver for the events field.
func (r *workflowLineageResolver) Events(ctx context.Context, obj *model.WorkflowLineage) ([]*model.Event, error) {
	lineage, err := r.Projector.GetLineage(obj.ID)
	if err != nil {
		return nil, err
	}
	res := mapToModel(lineage)
	return res.Events, nil
}

// RelatedLineages is the resolver for the relatedLineages field.
func (r *workflowLineageResolver) RelatedLineages(ctx context.Context, obj *model.WorkflowLineage) ([]*model.WorkflowLineage, error) {
	lineages, err := r.Projector.GetRelatedLineages(ctx, obj.ID)
	if err != nil {
		return nil, err
	}

	res := make([]*model.WorkflowLineage, 0, len(lineages))
	for _, l := range lineages {
		res = append(res, mapToModel(l))
	}
	return res, nil
}

// WorkflowLineage returns WorkflowLineageResolver implementation.
func (r *Resolver) WorkflowLineage() WorkflowLineageResolver { return &workflowLineageResolver{r} }

type workflowLineageResolver struct{ *Resolver }
