package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/customer"
	"github.com/GoHyperrr/hyperrr/internal/workflow"
)

// UpdateCustomer is the resolver for the updateCustomer field.
func (r *mutationResolver) UpdateCustomer(ctx context.Context, id string, input model.UpdateCustomerInput) (*model.Customer, error) {
	wf := &workflow.Workflow{
		Name: "customer.update",
		Steps: []workflow.Step{
			{ID: "customer.update_details", Uses: "customer.update_details"},
		},
	}

	workflowInput := map[string]any{
		"id": id,
	}
	if input.Name != nil {
		workflowInput["name"] = *input.Name
	}
	if input.Email != nil {
		workflowInput["email"] = *input.Email
	}

	execID := fmt.Sprintf("update_cust_%d", time.Now().UnixNano())
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	resRaw, ok := results["customer.update_details"]
	if !ok {
		return nil, fmt.Errorf("failed to retrieve updated customer from workflow results")
	}

	resMap, ok := resRaw.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("invalid result format from update step")
	}

	domainRes, ok := resMap["customer"].(*customer.Customer)
	if !ok {
		return nil, fmt.Errorf("invalid customer type in results")
	}

	res := &model.Customer{
		ID:      domainRes.ID,
		UserID:  domainRes.UserID,
		Name:    domainRes.Name,
		Email:   domainRes.Email,
		Persona: &domainRes.Persona,
	}

	for _, a := range domainRes.Addresses {
		res.Addresses = append(res.Addresses, &model.Address{
			ID:      a.ID,
			Line1:   a.Line1,
			Line2:   &a.Line2,
			City:    a.City,
			State:   a.State,
			Zip:     a.Zip,
			Country: a.Country,
		})
	}

	return res, nil
}

// GetCustomer is the resolver for the getCustomer field.
func (r *queryResolver) GetCustomer(ctx context.Context, id string) (*model.Customer, error) {
	c, err := r.CustomerModule.Repo().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	res := &model.Customer{
		ID:      c.ID,
		UserID:  c.UserID,
		Name:    c.Name,
		Email:   c.Email,
		Persona: &c.Persona,
	}

	for _, a := range c.Addresses {
		res.Addresses = append(res.Addresses, &model.Address{
			ID:      a.ID,
			Line1:   a.Line1,
			Line2:   &a.Line2,
			City:    a.City,
			State:   a.State,
			Zip:     a.Zip,
			Country: a.Country,
		})
	}

	return res, nil
}
