package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
)

// GetCustomer is the resolver for the getCustomer field.
func (r *queryResolver) GetCustomer(ctx context.Context, id string) (*model.Customer, error) {
	c, err := r.CustomerModule.Repo().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	res := &model.Customer{
		ID:      c.ID,
		UserID:  c.UserID,
		Name:    c.Name,
		Email:   c.Email,
		Persona: &c.Persona,
	}

	for _, a := range c.Addresses {
		res.Addresses = append(res.Addresses, &model.Address{
			ID:      a.ID,
			Line1:   a.Line1,
			Line2:   &a.Line2,
			City:    a.City,
			State:   a.State,
			Zip:     a.Zip,
			Country: a.Country,
		})
	}

	return res, nil
}
