package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/api/middleware"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, email string, password string, name string) (*model.AuthResponse, error) {
	actor, err := r.EmailPassModule.Register(ctx, email, password, name)
	if err != nil {
		return nil, err
	}

	token, err := r.EmailPassModule.Store().GenerateToken(*actor)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	return &model.AuthResponse{
		Token: token,
		Actor: &model.Actor{
			ID:   actor.ID,
			Type: string(actor.Type),
			Name: actor.Name,
		},
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string) (*model.AuthResponse, error) {
	actor, err := r.EmailPassModule.Login(ctx, email, password)
	if err != nil {
		return nil, err
	}

	token, err := r.EmailPassModule.Store().GenerateToken(*actor)
	if err != nil {
		return nil, fmt.Errorf("failed to generate token: %w", err)
	}

	return &model.AuthResponse{
		Token: token,
		Actor: &model.Actor{
			ID:   actor.ID,
			Type: string(actor.Type),
			Name: actor.Name,
		},
	}, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.Actor, error) {
	actor, ok := middleware.ForContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthorized")
	}

	return &model.Actor{
		ID:   actor.ID,
		Type: string(actor.Type),
		Name: actor.Name,
	}, nil
}
