package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
)

// GetPayment is the resolver for the getPayment field.
func (r *queryResolver) GetPayment(ctx context.Context, id string) (*model.Payment, error) {
	panic(fmt.Errorf("not implemented: GetPayment - getPayment"))
}

// ListOrderPayments is the resolver for the listOrderPayments field.
func (r *queryResolver) ListOrderPayments(ctx context.Context, orderID string) ([]*model.Payment, error) {
	panic(fmt.Errorf("not implemented: ListOrderPayments - listOrderPayments"))
}
