package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/fulfillment"
)

// UpdateShipmentStatus is the resolver for the updateShipmentStatus field.
func (r *mutationResolver) UpdateShipmentStatus(ctx context.Context, shipmentID string, trackingNumber *string, carrier *string) (*model.Shipment, error) {
	wf, err := r.Registry.Get("fulfillment.ship_order")
	if err != nil {
		return nil, err
	}

	workflowInput := map[string]any{
		"shipment_id": shipmentID,
	}
	if trackingNumber != nil {
		workflowInput["tracking_number"] = *trackingNumber
	}
	if carrier != nil {
		workflowInput["carrier"] = *carrier
	}

	execID := fmt.Sprintf("ship_%d", time.Now().UnixNano())
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	domainRes, ok := results["ship"].(*fulfillment.Shipment)
	if !ok {
		return nil, fmt.Errorf("failed to retrieve updated shipment from workflow results")
	}

	return mapShipmentToModel(domainRes), nil
}

// GetInventory is the resolver for the getInventory field.
func (r *queryResolver) GetInventory(ctx context.Context, productID string) (*model.Inventory, error) {
	inv, err := r.FulfillmentModule.Repo().GetInventoryByProductID(ctx, productID)
	if err != nil {
		return nil, err
	}
	return mapInventoryToModel(inv), nil
}

// GetShipment is the resolver for the getShipment field.
func (r *queryResolver) GetShipment(ctx context.Context, id string) (*model.Shipment, error) {
	s, err := r.FulfillmentModule.Repo().GetShipment(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapShipmentToModel(s), nil
}

// GetShipmentByOrder is the resolver for the getShipmentByOrder field.
func (r *queryResolver) GetShipmentByOrder(ctx context.Context, orderID string) (*model.Shipment, error) {
	s, err := r.FulfillmentModule.Repo().GetShipmentByOrderID(ctx, orderID)
	if err != nil {
		return nil, err
	}
	return mapShipmentToModel(s), nil
}
