package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/commerce/cart"
	"github.com/google/uuid"
)

// ApplyCouponToCart is the resolver for the applyCouponToCart field.
func (r *mutationResolver) ApplyCouponToCart(ctx context.Context, cartID string, couponCode string) (*model.Cart, error) {
	wf, err := r.Registry.Get("marketing.apply_coupon")
	if err != nil {
		return nil, err
	}

	// In a real system, cart.add_item would be specialized to handle discounts.
	// For now we'll just validate and then manually add a discount item to the cart.
	workflowInput := map[string]any{
		"cart_id":     cartID,
		"coupon_code": couponCode,
		"product_id":  "DISCOUNT_PROMO",
		"quantity":    1.0,
		"price":       0.0, // Simplified
	}

	execID := "promo_" + uuid.New().String()
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	// The cart.add_item handler returns the updated cart under step ID "apply"
	c, ok := results["apply"].(*cart.Cart)
	if !ok {
		// If apply didn't run because validate returned something else, just fetch the cart
		c, err = r.CartModule.Repo().GetByID(ctx, cartID)
		if err != nil {
			return nil, err
		}
	}

	return mapCartToModel(c), nil
}

// GetCoupon is the resolver for the getCoupon field.
func (r *queryResolver) GetCoupon(ctx context.Context, code string) (*model.Coupon, error) {
	c, err := r.MarketingModule.Repo().GetCouponByCode(ctx, code)
	if err != nil {
		return nil, err
	}
	return mapCouponToModel(c), nil
}

// GetLoyaltyBalance is the resolver for the getLoyaltyBalance field.
func (r *queryResolver) GetLoyaltyBalance(ctx context.Context, customerID string) (int, error) {
	lp, err := r.MarketingModule.Repo().GetLoyaltyPointsByCustomerID(ctx, customerID)
	if err != nil {
		return 0, nil // Default balance
	}
	return lp.Balance, nil
}
