package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/notification"
)

// ListNotifications is the resolver for the listNotifications field.
func (r *queryResolver) ListNotifications(ctx context.Context, recipient *string) ([]*model.Notification, error) {
	recip := ""
	if recipient != nil {
		recip = *recipient
	}

	notifs, err := r.NotificationModule.Repo().List(ctx, recip)
	if err != nil {
		return nil, err
	}

	res := make([]*model.Notification, 0, len(notifs))
	for _, n := range notifs {
		res = append(res, mapNotificationToModel(n))
	}

	return res, nil
}

func mapNotificationToModel(n *notification.Notification) *model.Notification {
	return &model.Notification{
		ID:        n.ID,
		Recipient: n.Recipient,
		Channel:   string(n.Channel),
		Subject:   n.Subject,
		Body:      n.Body,
		Status:    string(n.Status),
		CreatedAt: n.CreatedAt,
	}
}
