package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/order"
	"github.com/google/uuid"
)

// CreateOrderFromCart is the resolver for the createOrderFromCart field.
func (r *mutationResolver) CreateOrderFromCart(ctx context.Context, cartID string) (*model.Order, error) {
	c, err := r.CartModule.Repo().GetByID(ctx, cartID)
	if err != nil {
		return nil, fmt.Errorf("cart not found: %w", err)
	}

	if len(c.Items) == 0 {
		return nil, fmt.Errorf("cart is empty")
	}

	// Prepare workflow input
	items := make([]any, 0, len(c.Items))
	for _, item := range c.Items {
		items = append(items, map[string]any{
			"product_id": item.ProductID,
			"quantity":   float64(item.Quantity), // json/map expects float64 for numbers
			"price":      item.Price,
		})
	}

	workflowInput := map[string]any{
		"customer_id": c.CustomerID,
		"cart_id":     c.ID,
		"items":       items,
	}

	wf, err := r.Registry.Get("fulfillment.v1")
	if err != nil {
		return nil, err
	}

	execID := "fulfill_" + uuid.New().String()
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	oRaw, ok := results["order.finalize"]
	if !ok {
		oRaw, ok = results["order.create"]
	}
	if !ok {
		return nil, fmt.Errorf("failed to retrieve order from workflow results")
	}

	resMap, ok := oRaw.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("invalid result format from order step")
	}

	var o order.Order
	if err := decodeResult(resMap["order"], &o); err != nil {
		return nil, fmt.Errorf("invalid order type in results: %w", err)
	}

	return mapOrderToModel(&o), nil
}

// GetOrder is the resolver for the getOrder field.
func (r *queryResolver) GetOrder(ctx context.Context, id string) (*model.Order, error) {
	o, err := r.OrderModule.Repo().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapOrderToModel(o), nil
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*model.Order, error) {
	orders, err := r.OrderModule.Repo().List(ctx)
	if err != nil {
		return nil, err
	}

	res := make([]*model.Order, 0, len(orders))
	for _, o := range orders {
		res = append(res, mapOrderToModel(o))
	}
	return res, nil
}

// ListCustomerOrders is the resolver for the listCustomerOrders field.
func (r *queryResolver) ListCustomerOrders(ctx context.Context, customerID string) ([]*model.Order, error) {
	orders, err := r.OrderModule.Repo().ListByCustomerID(ctx, customerID)
	if err != nil {
		return nil, err
	}

	res := make([]*model.Order, 0, len(orders))
	for _, o := range orders {
		res = append(res, mapOrderToModel(o))
	}
	return res, nil
}
