package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/order"
	"github.com/GoHyperrr/hyperrr/internal/workflow"
)

// CreateOrderFromCart is the resolver for the createOrderFromCart field.
func (r *mutationResolver) CreateOrderFromCart(ctx context.Context, cartID string) (*model.Order, error) {
	c, err := r.CartModule.Repo().GetByID(ctx, cartID)
	if err != nil {
		return nil, fmt.Errorf("cart not found: %w", err)
	}

	if len(c.Items) == 0 {
		return nil, fmt.Errorf("cart is empty")
	}

	// Prepare workflow input
	items := make([]any, 0, len(c.Items))
	for _, item := range c.Items {
		items = append(items, map[string]any{
			"product_id": item.ProductID,
			"quantity":   float64(item.Quantity), // json/map expects float64 for numbers
			"price":      item.Price,
		})
	}

	workflowInput := map[string]any{
		"customer_id": c.CustomerID,
		"cart_id":     c.ID,
		"items":       items,
	}

	// Define Fulfillment Saga
	wf := &workflow.Workflow{
		Name: "fulfillment.v1",
		Steps: []workflow.Step{
			{
				ID:   "order.create",
				Uses: "order.create",
				Saga: &workflow.Saga{Uses: "order.compensate_payment"},
			},
			{
				ID:         "order.process_payment",
				Uses:       "order.process_payment",
				DependsOn:  []string{"order.create"},
			},
			{
				ID:         "order.finalize",
				Uses:       "order.finalize",
				DependsOn:  []string{"order.process_payment"},
			},
		},
	}

	execID := fmt.Sprintf("fulfill_%d", time.Now().UnixNano())
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	o, ok := results["order.finalize"].(*order.Order)
	if !ok {
		// Fallback to order from create step if finalize didn't return it for some reason
		o, ok = results["order.create"].(*order.Order)
		if !ok {
			return nil, fmt.Errorf("failed to retrieve order from workflow results")
		}
	}

	return mapOrderToModel(o), nil
}

// GetOrder is the resolver for the getOrder field.
func (r *queryResolver) GetOrder(ctx context.Context, id string) (*model.Order, error) {
	o, err := r.OrderModule.Repo().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapOrderToModel(o), nil
}

// ListOrders is the resolver for the listOrders field.
func (r *queryResolver) ListOrders(ctx context.Context) ([]*model.Order, error) {
	orders, err := r.OrderModule.Repo().List(ctx)
	if err != nil {
		return nil, err
	}

	res := make([]*model.Order, 0, len(orders))
	for _, o := range orders {
		res = append(res, mapOrderToModel(o))
	}
	return res, nil
}

// ListCustomerOrders is the resolver for the listCustomerOrders field.
func (r *queryResolver) ListCustomerOrders(ctx context.Context, customerID string) ([]*model.Order, error) {
	orders, err := r.OrderModule.Repo().ListByCustomerID(ctx, customerID)
	if err != nil {
		return nil, err
	}

	res := make([]*model.Order, 0, len(orders))
	for _, o := range orders {
		res = append(res, mapOrderToModel(o))
	}
	return res, nil
}
