package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/product"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	wf, err := r.Registry.Get("product.create")
	if err != nil {
		return nil, err
	}

	desc := ""
	if input.Description != nil {
		desc = *input.Description
	}

	workflowInput := map[string]any{
		"id":          input.ID,
		"name":        input.Name,
		"description": desc,
		"price":       input.Price,
	}

	execID := fmt.Sprintf("create_prod_%d", time.Now().UnixNano())
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	domainRes, ok := results["persist"].(*product.Product)
	if !ok {
		return nil, fmt.Errorf("failed to retrieve created product from workflow results")
	}

	return mapProductToModel(domainRes), nil
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	wf, err := r.Registry.Get("product.update")
	if err != nil {
		return nil, err
	}

	workflowInput := map[string]any{
		"id": id,
	}
	if input.Name != nil {
		workflowInput["name"] = *input.Name
	}
	if input.Description != nil {
		workflowInput["description"] = *input.Description
	}
	if input.Price != nil {
		workflowInput["price"] = *input.Price
	}

	execID := fmt.Sprintf("update_prod_%d", time.Now().UnixNano())
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	domainRes, ok := results["update"].(*product.Product)
	if !ok {
		return nil, fmt.Errorf("failed to retrieve updated product from workflow results")
	}

	return mapProductToModel(domainRes), nil
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	p, err := r.ProductModule.Repo().GetByID(ctx, id)
	if err != nil {
		return false, fmt.Errorf("product not found")
	}

	err = r.ProductModule.Repo().Delete(ctx, p.ID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// GetProduct is the resolver for the getProduct field.
func (r *queryResolver) GetProduct(ctx context.Context, id string) (*model.Product, error) {
	p, err := r.ProductModule.Repo().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return mapProductToModel(p), nil
}

// ListProducts is the resolver for the listProducts field.
func (r *queryResolver) ListProducts(ctx context.Context) ([]*model.Product, error) {
	products, err := r.ProductModule.Repo().List(ctx)
	if err != nil {
		return nil, err
	}

	res := make([]*model.Product, 0, len(products))
	for _, p := range products {
		res = append(res, mapProductToModel(p))
	}
	return res, nil
}
