package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/product"
	"github.com/google/uuid"
)

// SearchProducts is the resolver for the searchProducts field.
func (r *queryResolver) SearchProducts(ctx context.Context, query string, limit *int) ([]*model.Product, error) {
	wf, err := r.Registry.Get("search.products")
	if err != nil {
		return nil, err
	}

	lim := 10.0
	if limit != nil {
		lim = float64(*limit)
	}

	workflowInput := map[string]any{
		"query": query,
		"limit": lim,
	}

	execID := "search_" + uuid.New().String()
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	prodsRaw, ok := results["search"].([]*product.Product)
	if !ok {
		return nil, fmt.Errorf("failed to retrieve search results from workflow")
	}

	res := make([]*model.Product, 0, len(prodsRaw))
	for _, p := range prodsRaw {
		res = append(res, mapProductToModel(p))
	}
	return res, nil
}
