package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"time"

	"github.com/GoHyperrr/hyperrr/api/graph/model"
	"github.com/GoHyperrr/hyperrr/commerce/support"
	"github.com/GoHyperrr/hyperrr/internal/workflow"
)

// CreateTicket is the resolver for the createTicket field.
func (r *mutationResolver) CreateTicket(ctx context.Context, customerID string, subject string, message string) (*model.Ticket, error) {
	wf := &workflow.Workflow{
		Name: "support.create",
		Steps: []workflow.Step{
			{ID: "ticket", Uses: "support.create_ticket"},
			{ID: "ai_reply", Uses: "support.dispatch_ai_response", DependsOn: []string{"ticket"}},
		},
	}

	workflowInput := map[string]any{
		"customer_id": customerID,
		"subject":     subject,
		"message":     message,
	}

	execID := fmt.Sprintf("tkt_wf_%d", time.Now().UnixNano())
	results, err := r.Runner.Execute(ctx, execID, wf, workflowInput)
	if err != nil {
		return nil, err
	}

	// The CreateTicket handler returns map[string]any{"ticket": *support.Ticket}
	// The results map stores the output of each step under its ID.
	resRaw, ok := results["ticket"]
	if !ok {
		return nil, fmt.Errorf("missing ticket from workflow results")
	}
	resMap, ok := resRaw.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("invalid result format from ticket step")
	}
	t, ok := resMap["ticket"].(*support.Ticket)
	if !ok {
		return nil, fmt.Errorf("failed to retrieve ticket from results")
	}

	return mapTicketToModel(t), nil
}

// AddTicketMessage is the resolver for the addTicketMessage field.
func (r *mutationResolver) AddTicketMessage(ctx context.Context, ticketID string, sender string, content string) (*model.Message, error) {
	msg := &support.Message{
		ID:        fmt.Sprintf("msg_%d", time.Now().UnixNano()),
		TicketID:  ticketID,
		Sender:    support.SenderType(sender),
		Content:   content,
		CreatedAt: time.Now(),
	}

	if err := r.SupportModule.Repo().SaveMessage(ctx, msg); err != nil {
		return nil, err
	}

	return mapMessageToModel(msg), nil
}

// GetTicket is the resolver for the getTicket field.
func (r *queryResolver) GetTicket(ctx context.Context, id string) (*model.Ticket, error) {
	t, err := r.SupportModule.Repo().GetTicketByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapTicketToModel(t), nil
}

// ListCustomerTickets is the resolver for the listCustomerTickets field.
func (r *queryResolver) ListCustomerTickets(ctx context.Context, customerID string) ([]*model.Ticket, error) {
	tickets, err := r.SupportModule.Repo().ListTicketsByCustomerID(ctx, customerID)
	if err != nil {
		return nil, err
	}

	res := make([]*model.Ticket, 0, len(tickets))
	for _, t := range tickets {
		res = append(res, mapTicketToModel(t))
	}
	return res, nil
}
