// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Address struct {
	ID      string  `json:"id"`
	Line1   string  `json:"line1"`
	Line2   *string `json:"line2,omitempty"`
	City    string  `json:"city"`
	State   string  `json:"state"`
	Zip     string  `json:"zip"`
	Country string  `json:"country"`
}

type Customer struct {
	ID        string     `json:"id"`
	UserID    string     `json:"userId"`
	Name      string     `json:"name"`
	Email     string     `json:"email"`
	Persona   *string    `json:"persona,omitempty"`
	Addresses []*Address `json:"addresses"`
}

type Event struct {
	ID        string    `json:"id"`
	Type      string    `json:"type"`
	Timestamp time.Time `json:"timestamp"`
	Payload   *string   `json:"payload,omitempty"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	Price       float64 `json:"price"`
	Currency    string  `json:"currency"`
}

type Query struct {
}

type StepExecution struct {
	StepID    string     `json:"stepId"`
	State     string     `json:"state"`
	StartedAt time.Time  `json:"startedAt"`
	EndedAt   *time.Time `json:"endedAt,omitempty"`
	Attempts  int        `json:"attempts"`
	Error     *string    `json:"error,omitempty"`
}

type WorkflowLineage struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Version         string             `json:"version"`
	State           string             `json:"state"`
	StartedAt       time.Time          `json:"startedAt"`
	EndedAt         *time.Time         `json:"endedAt,omitempty"`
	Steps           []*StepExecution   `json:"steps"`
	Events          []*Event           `json:"events"`
	Error           *string            `json:"error,omitempty"`
	RelatedLineages []*WorkflowLineage `json:"relatedLineages"`
}
