package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func main() {
	// Look for hyperrr.yaml, hyperrr.yml, or hyperrr.json in the workspace root or configs/
	configPaths := []string{"hyperrr.yaml", "hyperrr.yml", "hyperrr.json", "configs/hyperrr.yaml", "configs/hyperrr.yml", "configs/hyperrr.json"}
	var configContent string
	var foundPath string

	for _, p := range configPaths {
		data, err := os.ReadFile(p)
		if err == nil {
			configContent = string(data)
			foundPath = p
			break
		}
	}

	if foundPath == "" {
		writeImports(nil)
		return
	}

	var imports []string
	reYAML := regexp.MustCompile(`resolve:\s*["']?([^"'\s]+)["']?`)
	reJSON := regexp.MustCompile(`"resolve":\s*["']?([^"'\s]+)["']?`)

	scanner := bufio.NewScanner(strings.NewReader(configContent))
	for scanner.Scan() {
		line := scanner.Text()
		var pkg string
		if matches := reYAML.FindStringSubmatch(line); len(matches) > 1 {
			pkg = matches[1]
		} else if matches := reJSON.FindStringSubmatch(line); len(matches) > 1 {
			pkg = matches[1]
		}

		if pkg != "" {
			// Exclude built-in modules which do not require blank imports (do not contain slashes)
			if strings.Contains(pkg, "/") {
				imports = append(imports, pkg)
			}
		}
	}

	writeImports(imports)
}

func writeImports(imports []string) {
	outPath := filepath.Join("internal", "app", "imports_generated.go")
	
	// Create directory if not exists
	_ = os.MkdirAll(filepath.Dir(outPath), 0755)

	var sb strings.Builder
	sb.WriteString("// Code generated by hyperrr. DO NOT EDIT.\n")
	sb.WriteString("package app\n\n")

	if len(imports) > 0 {
		sb.WriteString("import (\n")
		for _, imp := range imports {
			sb.WriteString(fmt.Sprintf("\t_ %q\n", imp))
		}
		sb.WriteString(")\n")
	}

	err := os.WriteFile(outPath, []byte(sb.String()), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to write generated imports: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s successfully with %d imports.\n", outPath, len(imports))
}
