package scaffold

const MainGoTemplate = `package main

import (
	"context"
	"fmt"
	"os"

	"github.com/GoHyperrr/hyperrr/internal/app"
	"github.com/GoHyperrr/hyperrr/pkg/config"
)

func main() {
	// Locate config path (fallback to local configs directory)
	cfgFile := "configs/hyperrr.yml"
	if _, err := os.Stat(cfgFile); os.IsNotExist(err) {
		cfgFile = "hyperrr.yml"
	}

	cfg, err := config.LoadWithFile(cfgFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Configuration error: %v\n", err)
		os.Exit(1)
	}

	if err := app.RunWithConfig(cfg); err != nil {
		fmt.Fprintf(os.Stderr, "Server failed to start: %v\n", err)
		os.Exit(1)
	}
}
`

const ImportsGoTemplate = `// Code generated by hyperrr. DO NOT EDIT.
package main

import (
{{- range .Modules }}
	_ "{{ .Resolve }}"
{{- end }}
)
`

const HyperrrYmlTemplate = `# Hyperrr configuration file for {{ .ProjectName }}
app_name: "{{ .ProjectName }}"
app_env: "local"
log_level: "info"
log_format: "text"
server_port: 8080

auth_providers:
  - jwt
mcp_auth_providers:
  - apikey

event_bus_provider: "{{ .EventBusProvider }}"
workflow_store_type: "mem"
db_driver: "{{ .DBDriver }}"
db_dsn: "{{ .DBDSN }}"
storage_provider: "cloud"
storage_bucket_url: "mem://"

modules:
{{- range .Modules }}
  - resolve: "{{ .Resolve }}"
    id: "{{ .ID }}"
{{- end }}
`

const DotEnvTemplate = `# Hyperrr Environment Variables
APP_ENV=local
SERVER_PORT=8080
LOG_LEVEL=info

# Database settings
DB_DRIVER={{ .DBDriver }}
DB_DSN={{ .DBDSN }}

# JWT secret (should be changed in production)
JWT_SECRET=super-secret-dev-token-secret-change-me-please-12345
JWT_EXPIRATION=24h
`

const GitIgnoreTemplate = `# Compiled test binaries
*.test
*.out
*.exe

# Local configs and databases
*.db
.env
bin/
dist/

# Auto-generated schemas directory for resolvers
api/graph/schema_gen/
`

const SchemaGraphqlsTemplate = `# Custom GraphQL schema extensions for {{ .ProjectName }}

# You can extend existing types from the loaded modules:
# extend type Query {
#   helloStore: String!
# }
`

const ReadmeTemplate = `# {{ .ProjectName }}

This is an AI-Native commerce engine built with **Hyperrr**.

## Getting Started

1. **Install dependencies**:
   ` + "```bash" + `
   go mod tidy
   ` + "```" + `

2. **Generate resolver codes**:
   ` + "```bash" + `
   # This will aggregate all module schemas, run gqlgen, and compile your local binary
   go run github.com/GoHyperrr/hyperrr/cmd/hyperrr@latest build
   ` + "```" + `

3. **Start the server**:
   ` + "```bash" + `
   ./bin/hyperrr server
   ` + "```" + `

## Project Structure

- ` + "`cmd/server/`" + `: Contains the entry point and imports setup for active modules.
- ` + "`configs/`" + `: Application configuration files (` + "`hyperrr.yml`" + `).
- ` + "`modules/`" + `: Put your custom project-specific modules here.
- ` + "`api/graph/`" + `: Custom GraphQL schema extensions and code-generated files.
`

const MakefileTemplate = `build:
	go run github.com/GoHyperrr/hyperrr/cmd/hyperrr@latest build

run: build
	./bin/hyperrr server

tidy:
	go mod tidy
`

const GoModTemplate = `module {{ .ModulePath }}

go 1.26

require (
	github.com/GoHyperrr/hyperrr v0.3.0
	github.com/GoHyperrr/mdk v0.3.0
)
`

