// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Event struct {
	ID        string    `json:"id"`
	Type      string    `json:"type"`
	Timestamp time.Time `json:"timestamp"`
	Payload   *string   `json:"payload,omitempty"`
}

type Query struct {
}

type StepExecution struct {
	StepID    string     `json:"stepId"`
	State     string     `json:"state"`
	StartedAt time.Time  `json:"startedAt"`
	EndedAt   *time.Time `json:"endedAt,omitempty"`
	Attempts  int        `json:"attempts"`
	Error     *string    `json:"error,omitempty"`
}

type WorkflowLineage struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Version         string             `json:"version"`
	State           string             `json:"state"`
	StartedAt       time.Time          `json:"startedAt"`
	EndedAt         *time.Time         `json:"endedAt,omitempty"`
	Steps           []*StepExecution   `json:"steps"`
	Events          []*Event           `json:"events"`
	Error           *string            `json:"error,omitempty"`
	RelatedLineages []*WorkflowLineage `json:"relatedLineages"`
}
