package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/GoHyperrr/hyperrr/internal/api/graph/model"
)

// GetProduct is the resolver for the getProduct field.
func (r *queryResolver) GetProduct(ctx context.Context, id string) (*model.Product, error) {
	p, err := r.ProductModule.Repo().GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:          p.ID,
		Name:        p.Name,
		Description: &p.Description,
		Price:       p.Price,
		Currency:    p.Currency,
	}, nil
}

// ListProducts is the resolver for the listProducts field.
func (r *queryResolver) ListProducts(ctx context.Context) ([]*model.Product, error) {
	products, err := r.ProductModule.Repo().List(ctx)
	if err != nil {
		return nil, err
	}

	res := make([]*model.Product, 0, len(products))
	for _, p := range products {
		res = append(res, &model.Product{
			ID:          p.ID,
			Name:        p.Name,
			Description: &p.Description,
			Price:       p.Price,
			Currency:    p.Currency,
		})
	}
	return res, nil
}
