name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout hyperrr
        uses: actions/checkout@v4
        with:
          path: hyperrr

      - name: Checkout mdk
        uses: actions/checkout@v4
        with:
          repository: GoHyperrr/mdk
          ref: ${{ github.head_ref || github.ref_name }}
          path: mdk

      - name: Checkout auth
        uses: actions/checkout@v4
        with:
          repository: GoHyperrr/auth
          ref: ${{ github.head_ref || github.ref_name }}
          path: auth

      - name: Checkout commerce
        uses: actions/checkout@v4
        with:
          repository: GoHyperrr/commerce
          ref: ${{ github.head_ref || github.ref_name }}
          path: commerce

      - name: Checkout file-storage
        uses: actions/checkout@v4
        with:
          repository: GoHyperrr/file-storage
          ref: ${{ github.head_ref || github.ref_name }}
          path: file-storage

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Setup Workspace
        run: |
          echo "go 1.25.5" > go.work
          echo "use (" >> go.work
          echo "    ./auth" >> go.work
          echo "    ./commerce" >> go.work
          echo "    ./file-storage" >> go.work
          echo "    ./hyperrr" >> go.work
          echo "    ./mdk" >> go.work
          echo ")" >> go.work

      - name: Go Vet
        run: cd hyperrr && go vet ./...

      - name: Go Test
        run: cd hyperrr && go test -v ./...

      - name: Go Build
        run: cd hyperrr && go build ./cmd/hyperrr
